name: CI/CD

on:
    push:
        paths:
        - 'SourceCode/**'
    pull_request:
        paths:
        - 'SourceCode/**'

jobs:
  linux:
    name: Linux-x86
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [g++, clang++]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install G++ Multilib, Clang++ & OpenGL library
        run: |
          sudo apt update
          sudo apt install -y g++-multilib clang libgl1-mesa-dev
          sudo apt install dos2unix
      
      # gendbg.sh is given write perms twice as a measure
      - name: Build
        run: |
          cd SourceCode/linux
          chmod +x gendbg.sh
          dos2unix gendbg.sh
          chmod +x gendbg.sh
          make COMPILER=${{ matrix.compiler }} CFG=release -j2
      
      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: Linux-x86-${{ matrix.compiler }}
          path: |
            SourceCode/linux/release/client.so
            SourceCode/linux/release/client.so.dbg
            SourceCode/linux/release/hl.so
            SourceCode/linux/release/hl.so.dbg
      
  win32:
    name: Win32
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86
      
      - name: Build
        run: msbuild SourceCode/projects/vs2019/HaloGS.sln -t:rebuild -property:Configuration=Release -maxcpucount:2 /p:AdditionalOptions="/std:c++20"
      
      - name: Deploy
        uses: actions/upload-artifact@v4
        with:
          name: Win32
          path: |
           SourceCode/projects/vs2019/Release/hl_cdll/client.dll
           SourceCode/projects/vs2019/Release/hl_cdll/client.pdb
           SourceCode/projects/vs2019/Release/hldll/hl.dll
           SourceCode/projects/vs2019/Release/hldll/hl.pdb
      